apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstore-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/bookstore-k8s-manifests
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: bookstore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bookstore-project
  namespace: argocd
spec:
  description: Bookstore application project
  sourceRepos:
  - 'https://github.com/your-username/bookstore-k8s-manifests'
  destinations:
  - namespace: bookstore
    server: https://kubernetes.default.svc
  - namespace: bookstore-staging
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: ''
    kind: Service
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: apps
    kind: Deployment
  - group: apps
    kind: ReplicaSet
  - group: networking.k8s.io
    kind: Ingress
  - group: autoscaling
    kind: HorizontalPodAutoscaler
  roles:
  - name: admin
    description: Admin privileges to bookstore project
    policies:
    - p, proj:bookstore-project:admin, applications, *, bookstore-project/*, allow
    - p, proj:bookstore-project:admin, repositories, *, *, allow
    groups:
    - bookstore-admins
  - name: developer
    description: Developer access to bookstore project
    policies:
    - p, proj:bookstore-project:developer, applications, get, bookstore-project/*, allow
    - p, proj:bookstore-project:developer, applications, sync, bookstore-project/*, allow
    groups:
    - bookstore-developers